config/routes.rb
Rails.application.routes.draw do
  resources :debts
  resources :customers
  devise_for :users
  get 'home' => 'home#index'

  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    return unless user.present?

    can :manage, Customer, user_id: user.id
    can :manage, Debt, user_id: user.id
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :debts
end

app/models/debt.rb
class Debt < ApplicationRecord
  belongs_to :user
  belongs_to :customer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  
    before_action :update_allowed_parameters, if: :devise_controller?
  
    protected
  
    def update_allowed_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :email, :password, :current_password)}
    end
  end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  load_and_authorize_resource

  # GET /customers or /customers.json
  def index
    @customers = Customer.where(user: current_user)
  end

  # GET /customers/1 or /customers/1.json
  def show
    @customer = Customer.find(params[:id])
    @debts = @customer.debts.order('created_at DESC')
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.user = current_user

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :pic, :address, :user_id)
    end
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
  load_and_authorize_resource

  # GET /debts/new
  def new
    @debt = Debt.new
    return unless params[:c]

    @customer = Customer.find(params[:c])
  end

  # GET /debts/1/edit
  def edit
  end

  # POST /debts or /debts.json
  def create
    @debt = Debt.new(debt_params)
    @debt.user = current_user
    
    respond_to do |format|
      if @debt.save
        format.html { redirect_to customer_url(params[:debt][:customer_id]), notice: "Debt was successfully created." }
        format.json { render :show, status: :created, location: @debt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debts/1 or /debts/1.json
  def update
    respond_to do |format|
      if @debt.update(debt_params)
        format.html { redirect_to customer_url(params[:debt][:customer_id]), notice: "Debt was successfully updated." }
        format.json { render :show, status: :ok, location: @debt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debts/1 or /debts/1.json
  def destroy
    @debt.destroy

    respond_to do |format|
      format.html { redirect_to debts_url, notice: "Debt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debt
      @debt = Debt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def debt_params
      params.require(:debt).permit(:amount, :user_id, :customer_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      return unless user_signed_in?
  
      redirect_to customers_path
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/views/customers/_customer.html.erb
<%= link_to customer_path(customer), class: "no-underline" do%>
<div class="flex box-shadow px-2 py-2 justify-between mt-4 items-center">
<div class="flex justify-center items-center gap-2">
<img src="<%= customer.pic %>" style="width: 80px; height: 80px; border-radius: 50%" >
<p class="p-0 m-0 text-[20px] font-bold"><%= customer.name %></p>
</div>
<p class="text-center text-[20px]">
$ <%= customer.debts.map{|s| s.amount}.sum %>
</p>
</div>
<% end %>

app/views/customers/_form.html.erb
<div class="w-full mt-4">
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field relative mb-4 px-3">
    <%= form.label :name, style: "display: block", class: "leading-7 text-xl text-gray-600 font-extrabold" %>
    <%= form.text_field :name, class: "w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-0 leading-8 transition-colors duration-200 ease-in-out" %>
  </div>

  <div class="field relative mb-4 px-3">
    <%= form.label :pic, style: "display: block", class: "leading-7 text-xl text-gray-600 font-extrabold" %>
    <%= form.text_field :pic, class: "w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-0 leading-8 transition-colors duration-200 ease-in-out" %>
  </div>

  <div class="field relative mb-4 px-3">
    <%= form.label :address, style: "display: block", class: "leading-7 text-xl text-gray-600 font-extrabold" %>
    <%= form.text_field :address, class: "w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-0 leading-8 transition-colors duration-200 ease-in-out" %>
  </div>

  <div class="absolute bottom-0 bg-[#00e7ff] w-full flex justify-center">
    <%= form.submit class: "bg-[#00e8ff] mt-4 text-white font-bold py-2 rounded flex justify-center px-20 border-0" %>
  </div>
<% end %>
</div>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<div class="w-[100%] h-[60px] bg-[#00E7FF] flex justify-between items-center text-white">
<div></div>
  <h2 class="m-0 tracking-wide text-2xl">CUSTOMERS</h2>
  <%= button_to destroy_user_session_path, method: :delete, class:"login-button" do %>
    <i class="fa-solid fa-right-from-bracket fa-2x" style="color: #ffffff;"></i>
    <% end %>
</div>

<div class="px-1">
<% if @customers.empty? %>
  <p>No customers available.</p>
<% else %>
  <% @customers.each do |customer| %>
    <%= render customer %>
    
  <% end %>
  <% end %>
</div>

<p style="color: green"><%= notice %></p>
<div class="absolute bottom-0 bg-[#00e7ff] w-full">
<%= link_to "New customer", new_customer_path, class: "bg-[#00e8ff] mt-4 text-white font-bold py-2 rounded flex justify-center px-20" %>
</div>

app/views/customers/new.html.erb
<div class="w-[100%] h-[60px] bg-[#00E7FF] flex justify-between items-center text-white">
  <%=link_to customers_path do%>
    <i class="fa-sharp fa-solid fa-arrow-left text-white fa-2x"></i>
  <%end%>
  <h2 class="m-0 tracking-wide text-2xl">NEW CUSTOMER</h2>
  <div></div>
</div>

<%= render "form", customer: @customer %>

app/views/customers/show.html.erb
<div class="w-full h-[60px] bg-[#00E7FF] flex justify-between items-center text-white">
  <%=link_to customers_path do%>
    <i class="fa-sharp fa-solid fa-arrow-left fa-2x text-white pl-2"></i>
  <%end%>
  <h2 class="m-0 tracking-wide text-2xl">Details</h2>
  <%= button_to destroy_user_session_path, method: :delete, class:"login-button" do %>
    <i class="fa-solid fa-right-from-bracket fa-2x pr-1" style="color: #ffffff;"></i>
  <% end %>
</div>
<div class="px-2 mt-3">
<div class="flex box-shadow px-2 py-2 justify-between">
<img src="<%= @customer.pic %>" style="width: 80px; height: 80px; border-radius: 50%" >
<div class="flex flex-col">
<p class="p-0 m-0 text-[20px] font-bold"><%= @customer.name %></p>
<%= link_to "Edit", edit_customer_path(@customer) %>
<%= button_to "Delete", @customer, method: :delete, class: "bg-[#00e7ff]" %>
</div>
</div>

<div>
    <h3 class="text-center text-[30px] font-extrabold">Transactions</h3>
    <% @debts.each do |debt| %>
      <div class="flex box-shadow px-3 py-2 justify-between items-center">
        <p class="text-[20px]">$   <strong><%= debt.amount %></strong></p>
        <div class="flex justify-center items-center gap-4">
          <p><%= debt.created_at.strftime('%m/%d/%Y') %></p>
          <%= button_to debt, method: :delete, class: "border-0 bg-[inherit]" do %>
          <i class="fa-sharp fa-solid fa-trash fa-2x"></i>
          <% end %>
        </div>
      </div>
    <% end %>
</div>
<p style="color: green"><%= notice %></p>
</div>
<div class="absolute bottom-0 bg-[#00e7ff] w-full">
<%= link_to "New Transaction", new_debt_path(:c => @customer.id), class: "bg-[#00e8ff] mt-4 text-white font-bold py-2 rounded flex justify-center px-20" %>
</div>

app/views/debts/_debt.html.erb
<div id="<%= dom_id debt %>">
  <p>
    <strong>Amount:</strong>
    <%= debt.amount %>
  </p>

  <p>
    <strong>User:</strong>
    <%= debt.user_id %>
  </p>

  <p>
    <strong>Customer:</strong>
    <%= debt.customer_id %>
  </p>

</div>

app/views/debts/_form.html.erb
<%= form_with(model: debt) do |form| %>
  <% if debt.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(debt.errors.count, "error") %> prohibited this debt from being saved:</h2>

      <ul>
        <% debt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field relative mb-4 px-3">
    <%= form.label :amount, style: "display: block", class: "leading-7 text-xl text-gray-600 font-extrabold" %>
    <%= form.number_field :amount, class: "w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-0 leading-8 transition-colors duration-200 ease-in-out" %>
  </div>
  <%= form.number_field :customer_id, value: @customer.id, class: "hidden w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-0 leading-8 transition-colors duration-200 ease-in-out" %>

  <div class="absolute bottom-0 bg-[#00e7ff] w-full flex justify-center">
    <%= form.submit class: "bg-[#00e8ff] mt-4 text-white font-bold py-2 rounded flex justify-center px-20 border-0" %>
  </div>
<% end %>

app/views/debts/edit.html.erb
<h1>Editing debt</h1>

<%= render "form", debt: @debt %>

<br>

<div>
  <%= link_to "Show this debt", @debt %> |
  <%= link_to "Back to debts", debts_path %>
</div>

app/views/debts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Debts</h1>

<div id="debts">
  <% @debts.each do |debt| %>
    <%= render debt %>
    <p>
      <%= link_to "Show this debt", debt %>
    </p>
  <% end %>
</div>

<%= link_to "New debt", new_debt_path %>

app/views/debts/new.html.erb
<div class="w-[100%] h-[60px] bg-[#00E7FF] flex justify-between items-center text-white">
  <%=link_to :back do%>
    <i class="fa-sharp fa-solid fa-arrow-left text-white fa-2x"></i>
  <%end%>
  <h2 class="m-0 tracking-wide text-2xl">NEW DEBT</h2>
  <div></div>
</div>

<%= render "form", debt: @debt %>

app/views/debts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @debt %>

<div>
  <%= link_to "Edit this debt", edit_debt_path(@debt) %> |
  <%= link_to "Back to debts", debts_path %>

  <%= button_to "Destroy this debt", @debt, method: :delete, class: "login-button" %>
</div>

app/views/home/index.html.erb
<section class='flex flex-col w-full h-[100vh] justify-center items-center'>
<h2 class="text-[40px]">C - Bill</h2>

<div class='flex flex-col justify-center items-center absolute bottom-0 w-full py-4'>
<%=link_to "Log in", new_user_session_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-4 rounded flex justify-center w-[90%]"%>
<%=link_to "Sign up", new_user_registration_path, class: 'text-grey no-underline mt-2'%>


</div>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CBill</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script>
    <script>tailwind.config = { corePlugins: { preflight: false } }</script>
    <script src="https://kit.fontawesome.com/b45a87b3cb.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <alert class="notice"><%= notice %></alert>
    <alert class="alert"><%= alert %></alert>
  </body>
</html>